pub_rate: 1.0 # Optional
base_path: 'Pepper' # Optional, prepended to all diagnostic output
analyzers:
  head:
    type: GenericAnalyzer
    path: Head
    startswith: 'head'
  hip:
    type: GenericAnalyzer
    path: Hip
    startswith: ['hip','knee']
  right_arm:
    type: GenericAnalyzer
    path: Right_Arm
    startswith: ['right'] 
  left_arm:
    type: GenericAnalyzer
    path: Left_Arm
    startswith: ['left'] 
